# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="dcadaadf-e29f-4cf6-ae26-7f96931344d0"

# Отправлять уведомление на почту a93357@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -youremail@smtp.ru
    on_success: never # default: change
    on_failure: always # default: always